# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='king', max_length=255)),
                ('password', models.CharField(default='1234567', max_length=255)),
            ],
            options={
                'db_table': 'tbl_user',
            },
        ),
    ]
